# Generated by Django 2.1 on 2018-08-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editrecipes', '0002_auto_20180809_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='peak',
            field=models.ManyToManyField(blank=True, related_name='peak_month', to='editrecipes.Month'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='tags',
            field=models.ManyToManyField(blank=True, to='editrecipes.Tag'),
        ),
    ]
