# Generated by Django 2.1 on 2018-08-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editrecipes', '0003_auto_20180809_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
