# Generated by Django 2.1 on 2018-08-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editrecipes', '0004_auto_20180809_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['name']},
        ),
    ]
