# Generated by Django 2.1 on 2018-08-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editrecipes', '0007_auto_20180825_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='sidedish',
            field=models.ManyToManyField(blank=True, to='editrecipes.SideDish'),
        ),
    ]
