# Generated by Django 2.1 on 2018-12-03 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editrecipes', '0010_auto_20181203_0936'),
        ('editrecipes', '0011_auto_20181203_0937'),
    ]

    operations = [
    ]
