# Generated by Django 2.1 on 2018-12-03 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editrecipes', '0012_merge_20181203_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='ingredientquantity',
            name='quantity',
        ),
        migrations.AddField(
            model_name='ingredientquantity',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='ingredientquantity',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='editrecipes.Unit'),
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
