# Generated by Django 2.1 on 2018-12-03 10:01

from django.db import migrations

def add_default_unit(apps, schema_editor):
    IngredientQuantity = apps.get_model('editrecipes', 'IngredientQuantity')
    Unit = apps.get_model('editrecipes', 'Unit')
    for iq in IngredientQuantity.objects.all():
        iq.unit = Unit.objects.get(name="item")
        iq.save()

class Migration(migrations.Migration):

    dependencies = [
        ('editrecipes', '0013_auto_20181203_0953'),
    ]

    operations = [
        migrations.RunPython(add_default_unit),
    ]
