# Generated by Django 2.1 on 2018-12-03 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editrecipes', '0014_auto_20181203_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='ingredientquantity',
            name='unit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='editrecipes.Unit'),
        ),
    ]
