# Generated by Django 2.1 on 2018-12-09 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editrecipes', '0016_auto_20181203_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientquantity',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ingredient_quantities', to='editrecipes.Recipe'),
        ),
    ]
