# Generated by Django 2.1 on 2018-12-12 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editrecipes', '0017_auto_20181209_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aisle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='editrecipes.Tag')),
            ],
        ),
    ]
