# Generated by Django 2.1 on 2019-07-08 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editrecipes', '0020_auto_20190708_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aisle',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='aisle',
            name='tag',
        ),
        migrations.AddField(
            model_name='aisle',
            name='name',
            field=models.CharField(default='unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='aisle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='editrecipes.Aisle'),
        ),
    ]
