# Generated by Django 2.1 on 2019-07-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editrecipes', '0021_auto_20190708_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='shortname',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
