# Generated by Django 2.1 on 2019-08-03 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editrecipes', '0024_recent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recent',
            name='meal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='editrecipes.Recipe'),
        ),
    ]
