# Generated by Django 2.1 on 2019-08-05 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editrecipes', '0025_auto_20190803_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('problem_ingredients', models.ManyToManyField(blank=True, related_name='guest_for_whom_problematic', to='editrecipes.Ingredient')),
                ('problem_tags', models.ManyToManyField(blank=True, related_name='guest_for_whom_problematic', to='editrecipes.Tag')),
            ],
        ),
        migrations.AlterField(
            model_name='recent',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editrecipes.Recipe'),
        ),
    ]
