# Generated by Django 3.0.1 on 2020-01-22 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editrecipes', '0026_auto_20190805_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='feeds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='final_unattended_cooking_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.DurationField(default=datetime.timedelta(0)),
            preserve_default=False,
        ),
    ]
