# Generated by Django 3.0.1 on 2020-01-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editrecipes', '0027_auto_20200122_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='final_unattended_cooking_time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='can_be_made_in_advance',
            field=models.BooleanField(default=False),
        ),
    ]
