# Generated by Django 3.0.1 on 2020-04-30 18:35

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('editrecipes', '0028_auto_20200122_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
        migrations.AlterModelOptions(
            name='recent',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='recent',
            name='meal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='editrecipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
