# Generated by Django 3.0.1 on 2020-04-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editrecipes', '0029_auto_20200430_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='editrecipes.IngredientQuantity', to='editrecipes.Ingredient'),
        ),
    ]
